
<div id="newsletter">
    <div class="inner">
    
        <p>Sign up now to be notified of the release of this engaging wine!</p>
        <form class="clearfix">
		<div class="form-item">
			<label>Enter Your Email Address_</label>
        	<input id="emailInput" type="email"  />
		</div>
		<div class="form-item">
        	<input type="submit" value="Submit" />
		</div>
        </form>
    
    </div>
</div>