
<div id="newsletter">
    <div class="inner">
    
        <p>Sign up now to be notified of the release of this engaging wine!</p>	
		
		<!-- Begin MailChimp Signup Form -->
		<div id="mc_embed_signup">
		<form action="http://hillsidewinery.us4.list-manage.com/subscribe/post?u=4aeedea4a328b0a2ce67cb63f&amp;id=5a4a91d18f" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate clearfix" target="_blank" novalidate>
		<div class="mc-field-group form-item">
			<label for="mce-EMAIL">Email Address_</label>
			<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
		</div>
			<div id="mce-responses form-item" class="clear">
				<div class="response" id="mce-error-response" style="display:none"></div>
				<div class="response" id="mce-success-response" style="display:none"></div>
			</div>	<div class="clear"><input type="submit" value="Submit" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
		</form>
		</div>
		
		<!--End mc_embed_signup-->		

    
    </div>
</div>