
<div id="footer-links" class="clearfix">

    <div class="grid grid-third little-miss-violin">
        <div class="inner">
            <a href="http://www.susannehou.com/" rel="external"><img src="<?php print path_to_theme() .'/images/little_miss_violin.png'; ?>" /></a>
        </div>
    </div>
    
    <div class="grid grid-third social-links">
        <div class="inner">
            <ul id="social">
                <li class="facebook"><a href="http://www.facebook.com" rel="external" title="Facebook">Facebook</a></li>
                <li class="twitter"><a href="http://twitter.com/200percent1" rel="external" title="Twitter">Twitter</a></li>
                <li class="youtube"><a href="https://www.youtube.com/user/TheClubHous" rel="external" title="YouTube">YouTube</a></li>
            </ul>
        </div>
    </div>
    
    <div class="grid grid-third hillside">
        <div class="inner">
            <a href="http://www.hillsidewinery.ca/" rel="external"><img src="<?php print path_to_theme() .'/images/hillside_winery.png'; ?>" /></a>
        </div>
    </div>

</div>